USER_ROLE_CHOICES = (
    ("USER", "USER"),
    ("UNIVERSITY-ADMIN", "UNIVERSITY-ADMIN"),

)
USER_POST_CHOICES = (
    ("AVAILABLE", "AVAILABLE"),
    ("PENDING", "PENDING"),
    ("FINISHED", "FINISHED"),
)

LOOKING_FOR_CHOICES = (
    ("ROOMMATES", "ROOMMATES"),
    ("PLACE", "PLACE"),
)

HOUSING_TYPE_CHOICES = (
    ("ON-CAMPUS", "ON-CAMPUS"),
    ("OFF-CAMPUS", "OFF-CAMPUS"),
)

MOVE_IN_CHOICES = (
    ("SUMMER", "SUMMER"),
    ("FALL", "FALL"),
    ("SPRING", "SPRING"),
)
