# Generated by Django 3.2 on 2022-03-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0005_alter_userposts__user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposts',
            name='_user',
        ),
        migrations.AddField(
            model_name='userposts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainweb.userregistration'),
        ),
    ]
