# Generated by Django 3.2 on 2022-03-08 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0007_rename_user_userposts_user_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 8)),
        ),
        migrations.AddField(
            model_name='userposts',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('ON-CAMPUS', 'ON-CAMPUS'), ('OFF-CAMPUS', 'OFF-CAMPUS')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='userposts',
            name='move_in',
            field=models.CharField(blank=True, choices=[('SUMMER', 'SUMMER'), ('FALL', 'FALL'), ('SPRING', 'SPRING')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userposts',
            name='no_of_bathrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userposts',
            name='no_of_bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(null=True, upload_to='posts/images')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.userposts')),
            ],
        ),
    ]
