# Generated by Django 3.2 on 2022-03-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0008_auto_20220308_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='main_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
