# Generated by Django 3.2 on 2022-03-16 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0013_auto_20220309_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 16)),
        ),
        migrations.CreateModel(
            name='UserContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('contacted_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainweb.userposts')),
            ],
        ),
    ]
