# Generated by Django 3.2 on 2022-03-17 09:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainweb', '0014_auto_20220316_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontacts',
            name='username',
        ),
        migrations.AddField(
            model_name='usercontacts',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='date',
            field=models.DateField(default=datetime.date(2022, 3, 17)),
        ),
    ]
