# Generated by Django 3.2 on 2022-03-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainweb', '0015_auto_20220317_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='date',
            field=models.DateField(),
        ),
    ]
